### ISSUE TITLE
difference of low , mid , high_extract.h5

### ISSUE THREAD

**Issue by Suqingyong** [Shawn-Shan/fawkes#100]
Dear sir, I am a little confused of these models: mid_extract.h5, high_extract.h5, low_extract.h5，is the performance of low_extract.h5 worse than mid_extract.h5 and high_extract.h5, or high_extract.h5 is used to generate high cloakes, low_extract.h5 is used to generate low cloakes ? Is there any connection between the model's performance and the name of model like "low", "high"? thanks!

**Comment by Suqingyong** [comment]
Dear sir, one more question, I have trained some models based on  tensorflow, how can I convert tensorflow model to h5 model based on keras that can be used directly in your code,  I have no idea about this , grateful to get advice from u,sir! Thank you .

**Comment by Shawn-Shan** [comment]
The mid_ low_ and high_ has no real meaning, - just some names I gave arbitrarily when doing the experiments. 

As for converting tf models to .h5 models, it is pretty complicated. I suggest you to change the source code of Fawkes to directly read your tf graph.
