### ISSUE TITLE
Some faces that cannot be detected will be cloaked.

### ISSUE THREAD

**Issue by MarkSCQ** [Shawn-Shan/fawkes#101]
I found that some images that Fawkes cannot detect faces in it will be added cloaks. 
![issues](https://user-images.githubusercontent.com/22400370/99895836-8f14d100-2c3f-11eb-8c09-4e133dfc16ca.PNG)

**Comment by Suqingyong** [comment]
At the beginning, I run the experiment with the cropped faces, the cloakes generation proceed normally. Later, I used some selfie photos but I found that the result of face detection and the cropped faces generated by the code are not exactly the face, i.e. the area of cropped is larger than the face, I do not know if it will influence the result of cloakes generation.

**Comment by Shawn-Shan** [comment]
The cropping algorithm is taken from FaceNet github repo, and it is a ML based model, so it is not perfect. I also found cases where it can not detect faces.
