### ISSUE TITLE
macOS 10.13 : I get an 'Illegal instruction: 4" on launch

### ISSUE THREAD

**Issue by freeeflyer** [Shawn-Shan/fawkes#103]
I tried to lauch 0.3, it crashes..

When launched in command line I get this error :

```
[nico@MacNico] ()  /Applications/Fawkes.app/Contents/MacOS
$ ./Fawkes
Illegal instruction: 4
```
Can anyone help ?

**Comment by Shawn-Shan** [comment]
We updated the mac version to 0.3.1. It should fix this issue.
