### ISSUE TITLE
"invalid instruction" error ("Недопустимая инструкция") 

### ISSUE THREAD

**Issue by Mister-N** [Shawn-Shan/fawkes#106]
Hello. I tried using fawkes and got the "invalid instruction" error ("Недопустимая инструкция") .

```
pip install fawkes
Collecting fawkes
  Using cached fawkes-0.3.2-py3-none-any.whl (29 kB)
.......
fawkes -d ./photo
Недопустимая инструкция
```
What processors does fawkes support? I have Linux Mint.  Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz processor.

**Comment by Shawn-Shan** [comment]
We should support most Intel core. Do you have any further information?
