### ISSUE TITLE
macOS 10.13 : I get an 'Illegal instruction: 4" on launch 

### ISSUE THREAD

**Issue by freeeflyer** [Shawn-Shan/fawkes#108]
Still getting the same result as in #103

Fawkes 0.3.1
macOS 10.13

Crashes on click, here is what that does when launching with command line

```
[nico@MacNico] ()  /Applications/Fawkes.app/Contents/MacOS
$ ./Fawkes
Illegal instruction: 4
```

**Comment by Shawn-Shan** [comment]
Can you try the 0.3 version? You can download that at this [link](https://mirror.cs.uchicago.edu/fawkes/files/0.3/Fawkes-0.3.dmg).

**Comment by freeeflyer** [comment]
> Can you try the 0.3 version? You can download that at this [link](https://mirror.cs.uchicago.edu/fawkes/files/0.3/Fawkes-0.3.dmg).

Hi.. 
I had the exact same error with 0.3. I opened the issue #103  for this, and you told me I had to try 0.3.1
I did and encountered the same issue.

**Comment by Shawn-Shan** [comment]
Can you try the binary version? If it does not work, would you paste the error messages here.

**Comment by freeeflyer** [comment]
> Can you try the binary version? If it does not work, would you paste the error messages here.

If by binary version you mean the dmg that's on your website, that's exactly the one I'm trying to use.

**Comment by freeeflyer** [comment]
> Can you try the binary version? If it does not work, would you paste the error messages here.

It says exactly the same thing:
```
[nico@MacNico] ()  ~/Downloads
$ ./protection-v0.3
Illegal instruction: 4
[nico@MacNico] ()  ~/Downloads
$ ./protection-v0.3 --help`
>
[nico@MacNico] ()  ~/Downloads
$ ./protection-v0.3 --help
Illegal instruction: 4
[nico@MacNico] ()  ~/Downloads
$ [nico@MacNico] ()  ~/Downloads
```

**Comment by xirkus** [comment]
No installation required: https://dev.scrb.ai

**Comment by Shawn-Shan** [comment]
Please try the newest v1.0 Mac version on our website.

**Comment by t-franz** [comment]
I downloaded the binary v1.0 from https://sandlab.cs.uchicago.edu/fawkes/#code an got the same error:
```
$ ./protection -d imgs/
Illegal instruction: 4
```
MacOS 10.13.6
(I tried the v1.0-DMG before and that didn't work either.)
