### ISSUE TITLE
Version 0.3.1 not working under macOS Big Sur 11.2 beta

### ISSUE THREAD

**Issue by PaulSherp** [Shawn-Shan/fawkes#109]
Version 0.3.1 does not appear to be working under macOS Big Sur 11.2 beta (20D5029f). As indicated in the OP, the application launches and is visible in the Dock, but does not show any window. Right-clicking on the Dock icon reveals that the application is not responding.

_Originally posted by @PaulSherp in https://github.com/Shawn-Shan/fawkes/issues/98#issuecomment-761837433_

**Comment by Shawn-Shan** [comment]
Is your Fawkes version 0.3.1? We should have fixed compatibility with MacOS 11.1. But we have not tested on 11.2 version.

**Comment by dasti555** [comment]
It's not working on 11.3 beta also.

**Comment by xirkus** [comment]
No debugging or dependency troubleshooting required: https://dev.scrb.ai

**Comment by Shawn-Shan** [comment]
Our tool at this point does not work on M1 Macbook. It is very hard to support M1 at this point.
