### ISSUE TITLE
 Compatibility for Windows 7 and other versions of Windnows

### ISSUE THREAD

**Issue by panderlad** [Shawn-Shan/fawkes#111]
Hello,

thanks for your software, but why you made it compatible only with Widows 10 and not other versions of Windows OS?

Most of the people don't use Windows 10.

So I cannot use it, and the binary code is difficult to use to normal users.

Can you make it compatible with all Windows versions?

**Comment by panderlad** [comment]
![image](https://user-images.githubusercontent.com/42316409/106384024-dc8c8780-63c0-11eb-9d1c-2b53d4d40273.png)

**Comment by panderlad** [comment]
I saw other users with Windows 10, have the same error, so it's not about the OS version.

**Comment by lnee94** [comment]
So I come from linux any way download and install python and pip (look it up on duckduckgo)
then open powershell and do 
pip install fawkes
so fawkes is instaled use the fawkes Comand and thats it

**Comment by xirkus** [comment]
If you just want to give it a try, you can use https://dev.scrb.ai

**Comment by emilywenger** [comment]
@xirkus Same comment here. 

re: the content of this post: a Windows update is imminent.

**Comment by Shawn-Shan** [comment]
Please try our newest v1.0 release on our website.
