### ISSUE TITLE
If the same images is cloaked 10 times, will be recognized as 10 different persons or as the same person?

### ISSUE THREAD

**Issue by panderlad** [Shawn-Shan/fawkes#112]

**Comment by Shawn-Shan** [comment]
The 10 cloaked images should be recognized as 10 different persons. 

We introduce randomness into Fawkes algorithm, so each time the cloak is computed it would be different. But we wouldn't recommend posting the same picture using 10 different cloaks.

**Comment by MarkSCQ** [comment]
In the paper, as Shawn mentioned, target selection is using randomness. In the code, the randomness about target selection is in utils.py and the description in the paper is in section 4.
