### ISSUE TITLE
Incompatible python dependencies

### ISSUE THREAD

**Issue by xirkus** [Shawn-Shan/fawkes#114]
There are a set of incompatible python dependencies with installing fawkes with pip:

- **ERROR:** fawkes 0.3.2 has requirement numpy==1.16.4, but you'll have numpy 1.16.5 which is incompatible.
- **ERROR:** scipy 1.6.0 has requirement numpy>=1.16.5, but you'll have numpy 1.16.4 which is incompatible.

The workaround is to pin `scipy` to version `1.5.4`. Might want to make this explicit in your requirements.txt.

**Comment by Shawn-Shan** [comment]
Thanks for bringing this up. The numpy requirement is not very crucial. I will fix it
