### ISSUE TITLE
Security vulnerabilities is specified tensorflow dependencies

### ISSUE THREAD

**Issue by xirkus** [Shawn-Shan/fawkes#115]
Can remediate most issues by upgrading to the latest patched version of 1.15.5 (although the recommended version is 2.4.0 according to Dependabot). Not sure if fawkes supports tensorflow 2.4.0 yet.

**Comment by MarkSCQ** [comment]
In the setup, it mentioned that Fawkes can only use tf<=1.15.  I tried to run it under tf 2.2 using Pycharm, but it is frozen. Migration from tf1 to tf2 might take some time. (^◕.◕^)

**Comment by Shawn-Shan** [comment]
Basically what @MarkSCQ said. Upgrading to tf2 requires some work, but we are actively working on a version with tf2 and better protection. Should come out in a month or so.
