### ISSUE TITLE
offtopic: your mailing-list link is broken

### ISSUE THREAD

**Issue by davecb** [Shawn-Shan/fawkes#119]
If I go to https://groups.google.com/g/fawkes-announce, I get 

> Content unavailable
> Double-check the link, or try switching accounts
> 

https://groups.google.com/access-error?continue=https://groups.google.com/g/fawkes-announce
![Screenshot_2021-02-07_12-30-34](https://user-images.githubusercontent.com/559505/107154313-516f3c80-6940-11eb-94fd-669d027b33cd.png)

**Comment by Shawn-Shan** [comment]
It seems to be an issue of googlegroup. We sent a report to google, but not sure if they will respond. We will manually add people for now. 

You can send us an email and we will add you.
