### ISSUE TITLE
App doesn't work on Mac OS Big sur 11.1

### ISSUE THREAD

**Issue by Mart29432** [Shawn-Shan/fawkes#120]
Hello, 
App doesn't work on my Mac OS Big Sur 11.1 I've been trying several times to download it and it never worked... Whether it doesn't even open, or it crashes once I try to upload an image to get protected... 
I downloaded the app on your website.

**Comment by dasti555** [comment]
The same issue, but it doesn't even start on 11.3 (Beta)

**Comment by sashachernysh** [comment]
Same here on 11.3

**Comment by xirkus** [comment]
If you want to give it a spin without tweaking the settings, I've set up the following: https://dev.scrb.ai

**Comment by emilywenger** [comment]
@xirkus Great that you set that up. However, our license stipulates that the Sandlab Fawkes copyright must be displayed whenever the source code is used elsewhere, as it is on your website. Please properly cite our work and provide correct attribution. Thanks in advance. 

re: the content of this issue: An update for Mac/Windows is imminent (next few days).

**Comment by xirkus** [comment]
Looking at your BSD License, I was unsure whether or not I could mention you:

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this list of conditions and the
  following disclaimer. <- Source code is not being redistributed.

* Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
  following disclaimer in the documentation and/or other materials provided with the distribution. <- No binary form
  is being distributed as well. This is a SaaS service. Not sure if this applies.

* Neither the name of the SANDLAB, University of Chicago nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. <- This is the clause in particular which I was concerned with. If you give me permission in writing, I will gladly mention your work.

**Comment by emilywenger** [comment]
Upon digging further, it appears you are attempting to form a company using Fawkes? (https://www.linkedin.com/company/scrb-ai/about/) This is obviously outside the allowed uses of this code base. See the Copyright section at the top of our README -- "This code is intended only for personal privacy protection or academic research".

The University of Chicago legal IP office will need to talk with you if you wish to continue forming a company based on our intellectual property. You can contact us at fawkes-team@googlegroups.com, and we will connect you to them. Thanks!

**Comment by xirkus** [comment]
You may want to review the difference between copyright vs. license before involving your UoC Legal department:

[What's the difference between Copyright and Licensing?](https://opensource.stackexchange.com/questions/297/whats-the-difference-between-copyright-and-licensing#:~:text=3%20Answers&text=Copyright%20is%20the%20legal%20term,to%20use%20the%20copyrighted%20material.&text=Only%20the%20copyright%20owner%20(or,in%20to%20a%20license%20agreement)

I'm not contesting your copyright. I fully acknowledge you and your team as the authors. The BSD License however what grants the terms of use. There is a _lot_ of commercial software built on BSD licensed code and this does require users of that code to ask for permission (as it is implicit in the License):

[Can I use new BSD licensed library/code in commercial closed source project?](https://softwareengineering.stackexchange.com/questions/165418/can-i-use-new-bsd-licensed-library-code-in-commercial-closed-source-project#:~:text=Yes.,the%20original%20copyright%20and%20license.&text=The%20BSD%20License%20allows%20proprietary,be%20incorporated%20into%20proprietary%20products.)

You're license is already included in your pypi repo, so no further need to "include" it when i deploy my solution.
