### ISSUE TITLE
Version drift between PyPi version (0.3.2) vs. this repo

### ISSUE THREAD

**Issue by xirkus** [Shawn-Shan/fawkes#121]
Are there any changes which need to be pushed into this repo to bring it up-to-date with the latest version published in pypi? The version in the __init__.py is 0.3.1, but the version in pypi is [0.3.2](https://pypi.org/project/fawkes/).

**Comment by Shawn-Shan** [comment]
The 0.3.2 update is only related to the mac app as MacOS updated to 10.14.
