### ISSUE TITLE
About the newest update

### ISSUE THREAD

**Issue by MarkSCQ** [Shawn-Shan/fawkes#124]
I noticed that Fawkes has migrated to TF2 recently and there are many changes in codes and functionalities, like removing min mode, custom mode, changing the parameters of low mid high mode, adding feature extractors ...

I want to know whether there is a description for all these changes, because I may miss some points when comparing the current codes with ones I have downloaded several months ago. 

Thank you so much.

**Comment by Shawn-Shan** [comment]
This is a still beta version and I am updating the software packages. Then I will provide a detailed lists as soon as possible

**Comment by MarkSCQ** [comment]
> This is a still beta version and I am updating the software packages. Then I will provide a detailed lists as soon as possible

Thank you so much :D

**Comment by jiapei100** [comment]
It looks keras is still used? Is it possible to use **tensorflow.keras** instead of **keras** itself?

`from tensorflow.keras.utils import Progbar` instead of `from keras.utils import Progbar`?
