### ISSUE TITLE
make load_extractor's model path ~/.fawkes or more user-configurable

### ISSUE THREAD

**Issue by stites** [Shawn-Shan/fawkes#128]
It looks like the intention is to make use of ~/.fawkes (from https://github.com/Shawn-Shan/fawkes/blob/master/fawkes/utils.py#L454). It could be nice, regardless, to have `~/.fawkes/models` be the default download site for transparency to the user in case of a corrupt download. Alternatively, this could be user-configurable which could require a bit of legwork.

For context I needed to make this patch: https://github.com/stites/fawkes/commit/6cc3bd85d34bb5e522be06fe1ef7a3f93b6b5317 to run fawkes on nixos (using mach-nix) due to nix's read-only filesystem constraint.

**Comment by Shawn-Shan** [comment]
This does make the code more configurable. However, the current implementation is easier for App packaging and distributing. Thus, we plan to keep as it is, and users who would like to configure should do so themselves. Thanks for bringing this up.
