### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Fc9Terminal** [Shawn-Shan/fawkes#13]
ERROR: Could not find a version that satisfies the requirement tensorflow<=1.15.0,>=1.12.0 (from fawkes) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2)
ERROR: No matching distribution found for tensorflow<=1.15.0,>=1.12.0 (from fawkes)

**Comment by DenisSouth** [comment]
You can try to run it on Google colab

**Comment by caretak3r** [comment]
> ERROR: Could not find a version that satisfies the requirement tensorflow<=1.15.0,>=1.12.0 (from fawkes) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2)
> ERROR: No matching distribution found for tensorflow<=1.15.0,>=1.12.0 (from fawkes)

@Fc9Terminal What version of python are you using? I had python3.8 locally, and saw that it requires the new version (v2) of tensorflow: https://www.tensorflow.org/install/pip

**Comment by Fc9Terminal** [comment]
@caretak3r, i am using Python 3.8.2 and pip 20.0.2

**Comment by DenisSouth** [comment]
> @caretak3r, i am using Python 3.8.2 and pip 20.0.2

Use Google colab

**Comment by caretak3r** [comment]
@Fc9Terminal can you try with a python between 3.5-3.8, and not 3.8?

**Comment by Shawn-Shan** [comment]
Yes, we do not support 3.8, because 3.8 does not support tensorflow 1
