### ISSUE TITLE
Slow processing time & minor issue for Apple's people album

### ISSUE THREAD

**Issue by Readilyield** [Shawn-Shan/fawkes#137]
Hi,
I am using Fawkes 1.0 on macOS 10.14
My pictures were taken via iPhone with average size of 2Mb, many of them contained more than one primary person in the centre.

When I cloaked my photos one by one, almost all of them took around 3 to 4 minutes to finish the process. And if I selected more than 20 photos and ran protection together it took nearly all night long. I wonder if it's the photo file's problem.

Also, I found that when I uploaded my cloaked photos back into Apple's photo, the app still recognised the faces in the people album. Is it because the underlying mechanism for Apple's photo different from general face recognition models or something else?

Thank you.

**Comment by emilywenger** [comment]
Hi, 

Cloaking involves some computationally intensive procedures, so the length of time you describe is typical for machines without GPU support. 

Fawkes is designed to poison the training datasets of future facial recognition models, not evade detection by existing models (this is explained clearly in our paper). Thus, it will not be effective against Apple Photo's already-trained facial recognition system.
