### ISSUE TITLE
cloaked jpg image looks very different compared to input 

### ISSUE THREAD

**Issue by chrisdane** [Shawn-Shan/fawkes#139]
Hi

I used fawkes to cloak 2 jpg images of 1200 x 1600 and 4608 x 3456 pixels (width x height), taken from different cams.

The small cloaked image looks very different compared to the input image, even with `-d low`. These differences are somewhat smaller in the large image case (also `-d low`), but I also can see the differences by eye in this case.

Hence, I cannot reproduce your examples at all with my own pictures.

I am using this binary: https://aur.archlinux.org/packages/fawkes-bin/.

Regards,  
Chris

**Comment by emilywenger** [comment]
Hi Chris, 

The visibility of the cloak depends on the input image. Typically, cloaks are must more visible on large, high-quality images (such as the ones you're trying to cloak). There is an inherent tradeoff between cloak visibility and protection quality.

**Comment by chrisdane** [comment]
Thanks for the answer. 

Could you give a hint which pixel sizes/image formats work best for fawkes to obtain a result similar to your examples (i.e. being indistinguishable by eye)?

Thanks!
Chris

**Comment by Pamalosebi** [comment]
Hi, just wanted to tell, that I had tried the same setup. And the results are frustratingly poor.

> I am using this binary: https://aur.archlinux.org/packages/fawkes-bin/.

But I also tried it (with exact the same source picture) then on windows. The results were really usable.

I can't tell what is wrong with the "fawkes-bin" using the AUR, but it is not working properly.
