### ISSUE TITLE
Confusion about your copyright & license

### ISSUE THREAD

**Issue by Yves-X** [Shawn-Shan/fawkes#14]
in README.md:
> # Copyright
> This code is intended only for personal privacy protection or academic research.
> We are currently exploring the filing of a provisional patent on the Fawkes algorithm.

The expression `personal privacy protection` lead to ambiguity. Only for personal use or only aimed at personal privacy?

In context that you mentioned patent, it sounds like you're stressing only for personal use.

However, the BSD 3-Clause "New" or "Revised" License you released on inclueds high-level **permission to commercial use**.

Is it a contradiction?

**Comment by t-vi** [comment]
What's more, there is this:
https://github.com/Shawn-Shan/fawkes/blob/3775bba1b42756ca0fb3e25500eee0b0622bcfe1/fawkes/detect_faces.py#L1-L3

The link goes to MIT licensed code. The MIT license requires you to reproduce copyright and permission notice to be included in all copies or substantial portions of the software.

**Comment by Shawn-Shan** [comment]
We have 1 year period to file for provisional patent. But in the meantime, we would like to release the code to help the public for privacy protection. More details in regarding to this will come shortly on our webpage. 

RE: I will append the MIT license to the code. Thanks for pointing this out.
