### ISSUE TITLE
MATPLOTLIBDATA environment variable and user name date

### ISSUE THREAD

**Issue by pivic** [Shawn-Shan/fawkes#15]
I'm using macOS Catalina and while fawkes works, it produces the following information in Terminal:

> /Users/sixiongshan/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py:493: MatplotlibDeprecationWarning:
> The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.

Even though this is not an issue, it mentions deprecation and contains a user name.

**Comment by Shawn-Shan** [comment]
Nice catch, I will fix this.
