### ISSUE TITLE
Fawkes not loading on Mac OS Monterey 12.1

### ISSUE THREAD

**Issue by alexk679** [Shawn-Shan/fawkes#154]
When I download it on my macbook it says "Fawkes Quit Unexpectedly" with options to reopen or ignore which do nothing.

When I restarted it still does not open but now that message is gone. Thanks

**Comment by Shawn-Shan** [comment]
Are you running on an Apple M1 chip machine? If so, we do not currently support it.

**Comment by iwill** [comment]
Fawkes does not work on my Mac: MacBook Pro (13-inch, M1, 2020) | macOS Monterey 12.1.

**Comment by Shawn-Shan** [comment]
We currently support M1 now. Pls check the website for the latest update.
