### ISSUE TITLE
All images in a directory aren't processed

### ISSUE THREAD

**Issue by pivic** [Shawn-Shan/fawkes#16]
I ran fawkes in a directory where I kept four images. Mind you, all of these images are of cartons and pens, so none contain any faces (neither human nor animal). Here's my log from running fawkes on macOS Catalina:

> ./protection -d Photos
> /Users/sixiongshan/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py:493: MatplotlibDeprecationWarning:
> The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
> Identify 4 images
> Find 0 face(s) in IMG_20200723_094514.jpg
> Find 0 face(s) in IMG_20200723_094438.jpg
> Find 0 face(s) in IMG_20200723_094603.jpg
> Find 2 face(s) in IMG_20200723_094526.jpg
> Attacker loaded
> 2 batches in total
> processing batch 0 at 2020-07-23 10:43:47.320197
> START: Total loss: 8.6843E-01; perturb: 0.000000 (0.00% over, raw: 0.000000); sim: 0.868433
> ITER    0 perturb: 0.00000; sim: 0.864359
> ITER   10 perturb: 0.00131; sim: 0.785477
> ITER   20 perturb: 0.00202; sim: 0.791557
> Learning Rate:  16.0
> ITER   30 perturb: 0.00202; sim: 0.791531
> ITER   40 perturb: 0.00202; sim: 0.791507
> END:       Total loss: 7.9148E-01; perturb: 0.000000 (raw: 0.002021); sim: 0.791484
> processing batch 1 at 2020-07-23 10:44:49.068363
> START: Total loss: 8.7156E-01; perturb: 0.000000 (0.00% over, raw: 0.000000); sim: 0.871560
> ITER    0 perturb: 0.00000; sim: 0.866800
> ITER   10 perturb: 0.00094; sim: 0.800822
> ITER   20 perturb: 0.00402; sim: 0.751458
> Learning Rate:  16.0
> ITER   30 perturb: 0.00219; sim: 0.788083
> ITER   40 perturb: 0.00219; sim: 0.788057
> END:       Total loss: 7.8803E-01; perturb: 0.000000 (raw: 0.002187); sim: 0.788033
> attack cost 108.277927 s
> attack cost 168.452666 s
> Done!

Only the images IMG_20200723_094514.jpg and IMG_20200723_094438.jpg generated cloaked versions. The two other ones remained untouched.

**Comment by Shawn-Shan** [comment]
From the log, the face extraction model did not identify any faces in IMG_20200723_094514, IMG_20200723_094438, and IMG_20200723_094603. 

Is the face too small in them?

**Comment by pivic** [comment]
Like I wrote, there are no faces in any of the pics... :)

**Comment by Shawn-Shan** [comment]
Oh I missed that. But yes, we only protect privacy for human at this point.

**Comment by pivic** [comment]
Thanks, @Shawn-Shan! I'm very happy to be trying out the tool!
