### ISSUE TITLE
Re-Cloaking Image

### ISSUE THREAD

**Issue by jdot274** [Shawn-Shan/fawkes#160]
Two questions –
1) If you run Fawkes on an already previously Cloaked image, will it work i.e. cloak the image again to avoid detection on a compromised once-cloaked image
2) What happens if you re-cloak the original image, will that work i.e. differently cloak the image each time

Thanks

**Comment by Shawn-Shan** [comment]
1. We do not recommend running Fawkes twice. 
2. It will be different each time.
