### ISSUE TITLE
Import error: from keras.utils import Progbar

### ISSUE THREAD

**Issue by rainmiuchen** [Shawn-Shan/fawkes#162]
After reinstalling  keras to the version your specified in requirement.txt, it still doesn't work.
change:
from keras.utils import Progbar
to:
from tensorflow.keras.utils import Progbar

**Comment by rainmiuchen** [comment]
reference website:
https://tensorflow.google.cn/api_docs/python/tf/keras/utils/Progbar

**Comment by Shawn-Shan** [comment]
I assume the issue is fixed after using tf.keras.
