### ISSUE TITLE
Installing Fawkes on M1 Mac results in "damaged" popup

### ISSUE THREAD

**Issue by jh1226** [Shawn-Shan/fawkes#163]
I was trying to install the newest version on Fawkes on my 2020 M1 MacBook Pro, as this newest version is said to be compatible with the M1 hardware. However, when I tried to run it after I installed it, this message popped up. No other explanation was given.
<img width="372" alt="Screenshot 2022-05-12 at 01 03 57" src="https://user-images.githubusercontent.com/22694862/167906898-6dc2e8a7-1769-4a65-8dfb-160ce5e98ea4.png">
.

**Comment by Shawn-Shan** [comment]
Did you set the security settings? Like the following: 

Setup Instructions: For MacOS, download the .dmg file and double click to install. If your Mac refuses to open because the APP is from an unidentified developer, please go to System Preference>Security & Privacy>General and click Open Anyway.

**Comment by jh1226** [comment]
That particular setting never did pop up. It went straight to saying it was damaged and cannot be open.

**Comment by Shawn-Shan** [comment]
This is fixed with a patch
