### ISSUE TITLE
Fawkes 1.0 make noises

### ISSUE THREAD

**Issue by offnightfollower** [Shawn-Shan/fawkes#164]
Why Fawkes makes noises/distortions on the picture, on their site all seems like good
![ImageGlass_es07y2eoDZ](https://user-images.githubusercontent.com/106079140/169812556-97bafdc9-4351-4b92-993e-c6d1f314954d.png)
p.s. its Windows version

**Comment by offnightfollower** [comment]
Thanks for the detailed answer

**Comment by Shawn-Shan** [comment]
Depends on the exact picture of the face, Fawkes adds different amount of noise. Some times, it requires enough noise (maybe human visible) to achieve protection.
