### ISSUE TITLE
illegal hardware instruction

### ISSUE THREAD

**Issue by yoy123** [Shawn-Shan/fawkes#165]
Compiled from command line on Mac OS 12.4 Intel MacPro5,1 using the following command:

 ~ % sudo python3 -m pip install https://files.pythonhosted.org/packages/55/1f/2788fa1579e474d4e937e8c274cd44f2e135b559ea838f24844fa4eae602/fawkes-1.0.4-py3-none-any.whl

Everything installed, no errors. But when I ran Fawkes from command line I got:
zsh: illegal hardware instruction  fawkes

I tried installing from home-brew and the prebuilt from the website and both do nothing. They look like they're gonna open and then just don't.

Any help would be awesome.

**Comment by Shawn-Shan** [comment]
I assume you have M1 chips. You will need to install numpy, tensorflow on M1 chips, which is very different from directly installing with pip. 

You can take a look at this tutorial. https://caffeinedev.medium.com/how-to-install-tensorflow-on-m1-mac-8e9b91d93706

But overall, it is hard to run on M1 chips using python. If you are just planning to cloak some images, you could download our pre-packaged APP on our website.
