### ISSUE TITLE
Attribute Error with Keras 'img_to_array'

### ISSUE THREAD

**Issue by thee-cos** [Shawn-Shan/fawkes#166]
Running fawkes v1.0.3 with keras v2.9.0 and keras-preprocessing v1.1.2 leads to an attribute error in utils.py line 109 img_to_array command

`.local/lib/python3.10/site-packages/fawkes/utils.py", line 109, in load_image
    image_array = image.img_to_array(img)
AttributeError: module 'keras.preprocessing.image' has no attribute 'img_to_array'
`

**Comment by Shawn-Shan** [comment]
We are not compatible with keras 2.9. Please downgrade keras to 2.4.3
