### ISSUE TITLE
Binaries for arm architecture (Raspberry PI)

### ISSUE THREAD

**Issue by f41ardu** [Shawn-Shan/fawkes#19]
Do you have any plans to issue a version for arm based architecture like Raspberry PI? 
Or might that be an performance issue? PI 4 may have appropriate resources. 

Thanks in advance

**Comment by Shawn-Shan** [comment]
There is no planned support for Arm architecture. 

You can potentially download the repo and run on Arm architecture. I am no expert on this ofc.
