### ISSUE TITLE
Can't pip install fawkes; Could not find a version that satisfies the requirement tensorflow<=1.15.0,>=1.12.0 (from fawkes)

### ISSUE THREAD

**Issue by LucasMW** [Shawn-Shan/fawkes#23]
`pip3 install fawkes`

> Collecting fawkes
>   Using cached fawkes-0.0.8-py3-none-any.whl (25 kB)
> Collecting scikit-image
>   Using cached scikit_image-0.17.2-cp38-cp38-macosx_10_13_x86_64.whl (12.2 MB)
> Collecting argparse
>   Downloading argparse-1.4.0-py2.py3-none-any.whl (23 kB)
> Collecting pillow>=7.0.0
>   Using cached Pillow-7.2.0-cp38-cp38-macosx_10_10_x86_64.whl (2.2 MB)
> Collecting numpy==1.16.4
>   Downloading numpy-1.16.4.zip (5.1 MB)
>      |████████████████████████████████| 5.1 MB 3.8 MB/s 
> Collecting keras<=2.3.1,>=2.2.5
>   Using cached Keras-2.3.1-py2.py3-none-any.whl (377 kB)
> Collecting bleach>=2.1.0
>   Using cached bleach-3.1.5-py2.py3-none-any.whl (151 kB)
> ERROR: Could not find a version that satisfies the requirement tensorflow<=1.15.0,>=1.12.0 (from fawkes) (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2)
> ERROR: No matching distribution found for tensorflow<=1.15.0,>=1.12.0 (from fawkes)
>

**Comment by M4cs** [comment]
Try using the `./setup.py` script from the repository. Clone it and then run it from within the cloned directory.

**Comment by Shawn-Shan** [comment]
Again, the current repo does not support python 3.8
