### ISSUE TITLE
Unable to install with current Tensorflow version

### ISSUE THREAD

**Issue by derritter88** [Shawn-Shan/fawkes#26]
Unfortunately PypI does not feature any tensorflow version > 2.2.0

Any chances to have fawkes running with the tensorflow version?

**Comment by Shawn-Shan** [comment]
As mentioned in several previous issues. We don't support python 3.8, because 3.8 does not support tf 1

**Comment by derritter88** [comment]
sorry - did not checked any previous bugs.
