### ISSUE TITLE
mtcnn.p.gz is not downloaded automatically

### ISSUE THREAD

**Issue by ilos-vigil** [Shawn-Shan/fawkes#3]
Hi, i wanted to try fawkes, but apparently `mtcnn.p.gz` isn't downloaded automatically and throws error instead.

```
$ fawkes -m low -d ./img
Traceback (most recent call last):
  File "/home/ilos-vigil/.local/bin/fawkes", line 8, in <module>
    sys.exit(main())
  File "/home/ilos-vigil/.local/lib/python3.6/site-packages/fawkes/protection.py", line 184, in main
    protector = Fawkes(args.feature_extractor, args.gpu, args.batch_size)
  File "/home/ilos-vigil/.local/lib/python3.6/site-packages/fawkes/protection.py", line 64, in __init__
    self.aligner = aligner(self.sess)
  File "/home/ilos-vigil/.local/lib/python3.6/site-packages/fawkes/align_face.py", line 16, in aligner
    pnet, rnet, onet = create_mtcnn(sess, None)
  File "/home/ilos-vigil/.local/lib/python3.6/site-packages/fawkes/detect_faces.py", line 262, in create_mtcnn
    fp = gzip.open(os.path.join(model_dir, "mtcnn.p.gz"), 'rb')
  File "/usr/local/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/usr/local/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/ilos-vigil/.fawkes/mtcnn.p.gz'
```

I had to download `mtcnn.p.gz` manually before fawkes running without any problem

```
cd ./fawkes
wget http://sandlab.cs.uchicago.edu/fawkes/files/mtcnn.p.gz
```

Additional information :
* Parrot Security 4.9 (Based on Debian 10 unstable/testing)
* Python 3.6.11 (compiled from source code)
* `fawkes` (version 0.0.7) is installed locally with command `pip3.6 install fawkes --user`

**Comment by Shawn-Shan** [comment]
All models should be downloaded to "/home/ilos-vigil/.fawkes/". Can you check whether "os.path.expanduser('~')" output the same path as "/home/ilos-vigil/"?

**Comment by ilos-vigil** [comment]
Other models downloaded automatically without any problem. Here's the output of `os.path.expanduser('~')`

```
$ python3.6
Python 3.6.11 (default, Jul 15 2020, 17:30:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.expanduser('~')
'/home/ilos-vigil'
>>>
```

**Comment by Shawn-Shan** [comment]
Thanks! 

Can you 1) rm  -r /home/ilos-vigil/.fawkes, 2) run the code again, 2) check whether "/home/ilos-vigil/.fawkes/mtcnn.p.gz" exist before you manual download?

**Comment by ilos-vigil** [comment]
I just tried your instruction and  "/home/ilos-vigil/.fawkes/mtcnn.p.gz" isn't exist. The error message is exactly same as well.

**Comment by sebastian-brandt** [comment]
Had the same issue. I installed with pip under Linux:
`pip3 install --user fawkes`
When starting fawkes, I got the same error message.
`cd ~/.fawkes ; wget http://sandlab.cs.uchicago.edu/fawkes/files/mtcnn.p.gz`
helped.

**Comment by berak** [comment]
similar problem, trying to run it on colab:
```
!git clone https://github.com/Shawn-Shan/fawkes
%cd fawkes
!wget http://sandlab.cs.uchicago.edu/fawkes/files/low_extract.h5
!wget http://sandlab.cs.uchicago.edu/fawkes/files/low_extract_emb.p.gz
!wget http://sandlab.cs.uchicago.edu/fawkes/files/mtcnn.p.gz

from fawkes import Fawkes
protector = Fawkes("low_extract", False, 1)
....
FileNotFoundError: [Errno 2] No such file or directory: '/root/.fawkes/mtcnn.p.gz'

!pwd
!ls
import os
os.path.expanduser('~')

/content/fawkes
app	    fawkes   low_extract_emb.p.gz  mtcnn.p.gz  setup.py
evaluation  LICENSE  low_extract.h5	   README.md

' /root' 
```

so, using `os.path.expanduser('~')` to resolve the path does not work for me here.

**Comment by Shawn-Shan** [comment]
Thanks for raising this issue. I will add an additional arguments to specific where the models are downloaded. It should fix the issue. 

In the meantime, you can run the Fawkes binary to cloak images (added support for linux).

**Comment by Shawn-Shan** [comment]
Alright, it should be fixed, please `pip install -U fawkes` or clone the newest repo.

**Comment by berak** [comment]
> I will add an additional arguments

https://github.com/Shawn-Shan/fawkes/blob/5a23532dd8a851022ca384ef6f657647ef629d57/fawkes/detect_faces.py#L258-L260

maybe you can make it respect, what's already given ?

`model_path` is never used, but overridden by code here

**Comment by olof-nord** [comment]
I experienced the same issue as @ilos-vigil - when using the [fawkes_binary_linux](http://sandlab.cs.uchicago.edu/fawkes/files/fawkes_binary_linux.zip) I initially got an error because of a missing file.

```
Traceback (most recent call last):
  File "fawkes/protection.py", line 191, in <module>
  File "fawkes/protection.py", line 184, in main
  File "fawkes/protection.py", line 64, in __init__
  File "fawkes/align_face.py", line 16, in aligner
  File "fawkes/detect_faces.py", line 262, in create_mtcnn
  File "gzip.py", line 53, in open
  File "gzip.py", line 163, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/home/olof/.fawkes/mtcnn.p.gz'
[12751] Failed to execute script protection
```
Downloading the file manually using the [link posted](http://sandlab.cs.uchicago.edu/fawkes/files/mtcnn.p.gz) and putting it in the `$HOME/.fawkes` folder solved the problem.

Python 3.8.3,
Arch Linux 5.7.6-arch1-1

**Comment by Shawn-Shan** [comment]
@olof-nord I just uploaded a new version of the linux binary with this bug fixed. 

In general, download the [mtcnn.p.gz](http://sandlab.cs.uchicago.edu/fawkes/files/mtcnn.p.gz) file to $HOME/.fawkes should fix this issue.

**Comment by ilos-vigil** [comment]
I upgraded fawkes to newest version (0.0.8), remove `~/.fawkes` and rerun the command `fawkes -m low -d ./img` without any problem.
Thanks for fixing the bug, i'm closing this issue.
