### ISSUE TITLE
Question -Is the cloaking random or algorithmic?

### ISSUE THREAD

**Issue by aendia777** [Shawn-Shan/fawkes#32]
I'm curious whether the cloaking that this program performs is random or algorithmic?

Let's say, for instance, someone uses Fawkes to cloak a facial image. If that same original facial image were to be cloaked by Fawkes in a separate instance, would the output be a completely unique cloaked image? Or would it be the same as the first cloaked image?

**Comment by Shawn-Shan** [comment]
The cloaking is randomize. It is randomized by the target label selection and also some inherent randomness in the stochastic optimization.
