### ISSUE TITLE
What happens if Fawkes is applied to its own output?

### ISSUE THREAD

**Issue by noel-yap** [Shawn-Shan/fawkes#38]
How many times can Fawkes be applied to its own output before humans can notice degradation in the image?

**Comment by Shawn-Shan** [comment]
Human perception is hard to quantify, so we don't know. And applying Fawkes more than once does not any additional protection. 

If you can tolerate the current perturbation, you can use mid or high mode for the cloak generation. It will have more noticable perturbation but more secure.

**Comment by noel-yap** [comment]
My question was geared more towards independent filters being applied
rather than about trying to increase security.

If you were to hazard a guess, would you say it would be closer to the
order of tens or hundreds or thousands or more?

**Comment by emjoywill** [comment]
It's really hard to say. Since this question is outside Fawkes' defined scope, we haven't considered the question. If you decide to run some experiments on your own, we'd be curious to hear the answer!
