### ISSUE TITLE
We have also done a similar work for privacy-preserving solution

### ISSUE THREAD

**Issue by LanZhang** [Shawn-Shan/fawkes#39]
Dear authors，
We have also done a similar work that developing a privacy-preserving solution, called Adversarial Privacy-preserving Filter (APF), to protect the online shared face images from being maliciously used. We propose the end-cloud collaborated adversarial attack solution to satisfy the absolute privacy-preserving. This work has been accepted by ACM Multimedia 2020, which is available at https://arxiv.org/abs/2007.12861. Welcome to discuss for any questions and future works.

Regards

**Comment by Shawn-Shan** [comment]
This is awesome! Thanks Lan for sharing!
