### ISSUE TITLE
No description for the command line utility parameters in readme

### ISSUE THREAD

**Issue by Retew** [Shawn-Shan/fawkes#40]
For me default settings worked really bad making me essentially look like an alien on a resulting photo. However, `--help` suggests there is `--mode` parameter. I think, if I change the mode it might work well for me, but I could not find description of modes anywhere, so I don't know, what values it can accept. There is also no description of any other parameters neither on your website nor in the readme. Most of the parameters described in `--help` output also have no annotations, so I have no idea what they do. Please fix it.

**Comment by Shawn-Shan** [comment]
Yes, we plan to add this.
