### ISSUE TITLE
Exception: No faces detected

### ISSUE THREAD

**Issue by monterrr** [Shawn-Shan/fawkes#41]
Doesn't work for me on a highly edited black and white image with sunglasses, does it need to detect a face to process an image?

```
Identify 1 files in the directory
Identify 1 images in the directory
Find 0 face(s)
Traceback (most recent call last):
  File "fawkes/protection.py", line 210, in <module>
  File "fawkes/protection.py", line 206, in main
  File "fawkes/protection.py", line 106, in run_protection
  File "fawkes/utils.py", line 165, in __init__
Exception: No faces detected
[114120] Failed to execute script protection

```

**Comment by Shawn-Shan** [comment]
The current software only generate protection if it detected a face in the image. We use a face detector, which of course is not perfect. I will add an option that will bypass this detection step and generate cloak even without detecting faces.

**Comment by monterrr** [comment]
And what about when applying the modifications to a black and white picture to leave it in greyscale instead of adding color?

**Comment by emjoywill** [comment]
Cloaking on a B&W facial image works just fine -- see picture of Ben on our project website (http://sandlab.cs.uchicago.edu/fawkes/).

**Comment by monterrr** [comment]
Yes it works but for me it introduced color in a black and white picture, needing to convert the image again after that to grayscale color space.
