### ISSUE TITLE
Programm crashes insted to protect pictures

### ISSUE THREAD

**Issue by transafrika** [Shawn-Shan/fawkes#42]
I selected 1072 pictures each one just 200kb just to find the program crashed "An Error acoured. This program has to be closed" under Win10 after i came back from work :-(

**Comment by Shawn-Shan** [comment]
wow that is a lot of pictures. Probably because the program uses too much memory and crashed. 

Please try less images at a time and see whether it helps.

**Comment by transafrika** [comment]
Thanks i try it says 46 scince 4 hours...

**Comment by transafrika** [comment]
Program has been working the whole night but after 12 hours still no changes. 

Then i tred with one single image. It said 1 minute and after 1 hour it really produced a new image called originalname_low_cloaked.png. 

That does not help im shure most of the people need the same name and if possible the same file type as before without having to manually change it again...

Thanks a lot anyway 👍

**Comment by emjoywill** [comment]
Hi! Creating cloaks requires a significant amount of local compute power. Depending on your local machine specs, this may result in the cloaking taking a long time (as you experienced). 

Right now, the cloaked images aren't saved to your computer until cloaks for *all* selected images have been computed. This would explain the perceived lack of program progress after 12 hours. It's probably the case that the program had already finished several cloaks but you had no indicator of this. In future versions of the code, we will move cloaked image saving earlier so you can more readily see progress. 

We intentionally wrote the program to save cloaked images under a different name so users could easily distinguish between the original and cloaked versions. There may be instances where users wish to have both versions. Feel free to rename the cloaked file as you wish. 

Thanks for the feedback!

**Comment by transafrika** [comment]
Answer: https://github.com/Shawn-Shan/fawkes/issues/45
