### ISSUE TITLE
Wrong filenames better keep original name

### ISSUE THREAD

**Issue by transafrika** [Shawn-Shan/fawkes#45]
Cloaked images are not saved under the original filename. Fir people who want to protect more then 1000 pictures of an existing blog etc 

>>Feel free to rename the cloaked file as you wish.

Cant be a acceptable solution. Just a little checkbox or question if you want to overwrite existing files or create copies would save a LOT of nonsense work manually renaming more then 1000 pictures is not an option...

Thanks :)

**Comment by emjoywill** [comment]
Thanks for your input! We will certainly keep this in mind for future releases.
