### ISSUE TITLE
Error while installing with pip

### ISSUE THREAD

**Issue by J053Fabi0** [Shawn-Shan/fawkes#46]
```
ERROR: Could not find a version that satisfies the requirement tensorflow<=1.15.0,>=1.12.0 (from fawkes) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow<=1.15.0,>=1.12.0 (from fawkes)
```
I get this error when I run `sudo pip install fawkes`, even after I successfully run `sudo pip install tensorflow`.

**Comment by andriisgit** [comment]
> ```
> ERROR: Could not find a version that satisfies the requirement tensorflow<=1.15.0,>=1.12.0 (from fawkes) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
> ERROR: No matching distribution found for tensorflow<=1.15.0,>=1.12.0 (from fawkes)
> ```
> 
> I get this error when I run `sudo pip install fawkes`, even after I successfully run `sudo pip install tensorflow`.

I got the same error.
Which version of Python should be ? 
Is it possible to raise in requirements the tensorflow version up to current 2.3 ?

**Comment by Shawn-Shan** [comment]
The code does not support tensorflow >2.0. You will need python < 3.8 to run.
