### ISSUE TITLE
port to Android and iOS?

### ISSUE THREAD

**Issue by n8fr8** [Shawn-Shan/fawkes#49]
Hey Fawkes team - great work. I've been hoping for something like this for awhile, and even experimented with more visible perturbation, but nothing as clean as what you have done.

I'm the lead developer at Guardian Project, a privacy-focused open-source mobile team, and we've helped groups like Tor, GPG, SQLCipher and others get their tech onto mobile devices. We also built [ObscuraCam](https://guardianproject.info/apps/obscuracam/) almost 10 years ago, and app focused on visual privacy and metadata cleaning. I think having Fawkes built into ObscuraCam would make a great deal of sense.

Other than resources or time, what are your concerns or challenges with bringing Fawkes to mobile?

**Comment by Shawn-Shan** [comment]
Thanks for your interests in your project. The challenge of porting to mobile is computation power. Currently, the algorithm runs ~1 mins on a decent laptop, and I am not sure how long this translate to mobile compute time. But this is definitely really cool, and we can perhaps develop a simplified version of Fawkes that can run on mobile devices.

**Comment by n8fr8** [comment]
I'll stay tuned! We are starting to use some mobile ML engines like ML Kit and Tensor Mobile, with promising possibilities.

**Comment by Mtemi** [comment]
Would I be able to use ML Kit or Tensor Mobile in processing of Camera
text? Example !  I would like to point a camera to whatsapp web and read
text messages then process certain messages by use of ML Kit, do
calculations and post results back to whatsapp.

**Comment by mptorz** [comment]
Hey, is anyone currently working on porting it to mobile? If not I might give it a go and experiment a little bit :)

**Comment by Shawn-Shan** [comment]
The computation cost would be the biggest challenge (I expect the implementation should be straightforward). I suggest you to look into how to reduce the computation cost without sacrificing protection.

**Comment by Artoria2e5** [comment]
The “easy” implementation might be a warm-powered PWA with https://github.com/pyodide/pyodide, but since no GPU is provided on wasm it’s going to be painful. It would still be really useful to do it on mobile though — that’s how most selfies are taken these days.
