### ISSUE TITLE
Linux binary outputs an error

### ISSUE THREAD

**Issue by onion-overdose** [Shawn-Shan/fawkes#5]
I can't use the linux binary, I'm using Manjaro linux. It is outputting this error

 
![error](https://user-images.githubusercontent.com/58173986/87770470-b0525480-c83c-11ea-9c6b-89727920ebb2.png)
   
   
How can I resolve this?

**Comment by Shawn-Shan** [comment]
I updated a new version of the linux binary on the website. Should fix this issue.
