### ISSUE TITLE
Can't install on linux/windows with pip3

### ISSUE THREAD

**Issue by Gigabait** [Shawn-Shan/fawkes#51]
Hello, i have trouble with install this packet on linux and windows systems.
```
ERROR: Could not find a version that satisfies the requirement tensorflow<=1.15.0,>=1.12.0 (from fawkes) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)                     
ERROR: No matching distribution found for tensorflow<=1.15.0,>=1.12.0 (from fawkes)  
```
What i need to do for fix this problem ?

**Comment by Gigabait** [comment]
So, i found answer. I need use python < 3.8 :/

**Comment by Gigabait** [comment]
I try download it on 3.7 version but i get same error.
`ERROR: Could not find a version that satisfies the requirement tensorflow<=1.15.0,>=1.12.0 (from fawkes) (from versions: none)
ERROR: No matching distribution found for tensorflow<=1.15.0,>=1.12.0 (from fawkes)`

**Comment by Mtemi** [comment]
Should be an issue not related to fawkes but python environment

**Comment by Gigabait** [comment]
Yes, there might be a problem in python environment. Anyway i found compiled version for windows.
