### ISSUE TITLE
V0.3 error on Windows

### ISSUE THREAD

**Issue by javad94** [Shawn-Shan/fawkes#55]
Version 0.3 which downloaded from [here](https://mirror.cs.uchicago.edu/fawkes/files/0.3/Fawkes-0.3.exe) for windows gives "Failed to execute script app_qr" error when running on Windows 10.  

![image](https://user-images.githubusercontent.com/7765309/89712464-409c3900-d9a6-11ea-86ba-a50c45390b8c.png)

**Comment by emjoywill** [comment]
Can you provide more information? How old is your Windows computer? Can you re-download the app and try again? It may be the case that the download was corrupted.
