### ISSUE TITLE
.fawkes is incomplete causing an error

### ISSUE THREAD

**Issue by c947694498** [Shawn-Shan/fawkes#58]
During the first run, if the download of the resources downloaded by the .fawkes fails, an error will occur and the resources downloaded by the .fawkes need to be verified.

**Comment by emjoywill** [comment]
Thanks for the feedback. Was there anything we need to resolve here? It looks like you just need to make sure your download is not interrupted.

**Comment by Shawn-Shan** [comment]
We will add a checksum to make sure the download is successful.
