### ISSUE TITLE
Error while processing image

### ISSUE THREAD

**Issue by distantsky** [Shawn-Shan/fawkes#6]
Program throws an error on Ubuntu 18.4.4

![protection-error](https://user-images.githubusercontent.com/5034460/87852635-2e713280-c8f3-11ea-914b-db8461e3663b.png)

**Comment by Shawn-Shan** [comment]
Thanks for raising this issue!

It seems that you have 2 files in the directory but one of them is not an image file. If that is the case, simply remove that file should fix the error. I will make a patch to ignore any non-image file in the directory.
