### ISSUE TITLE
can't download model

### ISSUE THREAD

**Issue by FBEMPSS** [Shawn-Shan/fawkes#60]
when downloading models,get an error.

Exception: URL fetch failure on http://mirror.cs.uchicago.edu/fawkes/files/high_extract.h5: 503 -- Service Temporarily Unavailable

how can i get the model pls
i have used vpn ,but it is no use

**Comment by emjoywill** [comment]
This is likely due to a network failure. Perhaps your VPN settings do not allow this kind of fetch? Please check your network settings and try again.
