### ISSUE TITLE
No matching distribution found for tensorflow<=1.15.0,>=1.12.0

### ISSUE THREAD

**Issue by g-w1** [Shawn-Shan/fawkes#64]
When I try to install fawkes this is what happens
```[user ~]$ sudo pip install fawkes
Collecting fawkes
  Using cached fawkes-0.0.8-py3-none-any.whl (25 kB)
Collecting bleach>=2.1.0
  Using cached bleach-3.1.5-py2.py3-none-any.whl (151 kB)
Requirement already satisfied: pillow>=7.0.0 in /usr/lib/python3.8/site-packages (from fawkes) (7.2.0)
ERROR: Could not find a version that satisfies the requirement tensorflow<=1.15.0,>=1.12.0 (from fawkes) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1,
2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow<=1.15.0,>=1.12.0 (from fawkes)
[user ~]$
```
I am running archlinux x86-64.
Could this be an upstream issue?

**Comment by emjoywill** [comment]
Have you installed the tensorflow package?

**Comment by g-w1** [comment]
No. Shouldn't fawkes install it for me?

I did ``sudo pip install tensowflow`` I think that it wants a specific version of tensorflow that does not exist. Ill try to take a look at setuptools when I have time.

**Comment by Shawn-Shan** [comment]
I believe you are using python 3.8. We do not support 3.8. Please downgrade to 3.7 to run.

**Comment by g-w1** [comment]
Ah yes. Thanks.
