### ISSUE TITLE
 Failed to execute script protection

### ISSUE THREAD

**Issue by zhangmingjiang1114** [Shawn-Shan/fawkes#66]
Based on win10 system and python3.5, how to solve this problem, thank you very much! Questions are as follows:
E:\fawkes>protection-v0.3.exe -d E:\fawkes\images
Traceback (most recent call last):
  File "protection.py", line 225, in <module>
  File "protection.py", line 210, in main
  File "protection.py", line 52, in __init__
  File "align_face.py", line 44, in aligner
  File "detect_faces.py", line 285, in create_mtcnn
  File "gzip.py", line 276, in read
  File "_compression.py", line 68, in readinto
  File "gzip.py", line 482, in read
EOFError: Compressed file ended before the end-of-stream marker was reached
[11268] Failed to execute script protection

**Comment by Shawn-Shan** [comment]
Seems the network failed when downloading the model, so you got an corrupted file. Please remove ~/USERNAME/.fawkes folder and rerun the binary with good network connections.

**Comment by zhangmingjiang1114** [comment]
> Seems the network failed when downloading the model, so you got an corrupted file. Please remove ~/USERNAME/.fawkes folder and rerun the binary with good network connections.

我删了原来的文件夹后，重新git clone了fawkes文件夹，还是报了同样的错误，不知道啥原因。难道是protection-v0.3.exe文件的问题么，protection-v0.3.exe是解压缩出来的。求助啊？

**Comment by zhangmingjiang1114** [comment]
> Seems the network failed when downloading the model, so you got an corrupted file. Please remove ~/USERNAME/.fawkes folder and rerun the binary with good network connections.

After deleting the original folder, I git cloned the fakes folder again, and the same error was reported, but I don't know the reason. Is it a problem with the protection-v0.3.exe file? Protection-v0.3.exe is decompressed. How to solve?Thank you!!!

**Comment by MarkSCQ** [comment]
> > Seems the network failed when downloading the model, so you got an corrupted file. Please remove ~/USERNAME/.fawkes folder and rerun the binary with good network connections.
> 
> After deleting the original folder, I git cloned the fakes folder again, and the same error was reported, but I don't know the reason. Is it a problem with the protection-v0.3.exe file? Protection-v0.3.exe is decompressed. How to solve?Thank you!!!

哥们儿，你试试wsl吧，我wsl能run, 但是用的是CPU，wsl的GPU我懒得折腾  -.-
我Win下能跑exe 但是python file没法跑，即便我更改了所有的环境，tf,keras版本配置。
挺头疼的。我想换pytorch了，太痛苦了

**Comment by MarkSCQ** [comment]
![image](https://user-images.githubusercontent.com/22400370/98417487-d4c57d00-2035-11eb-8df9-aeeffddf9c99.png)
Hi @Shawn-Shan, I tried to install different versions of Tensorflow and Keras, but the same error appears.

**Comment by Shawn-Shan** [comment]
Did you install tensorflow-gpu or tensorflow? You will need tensorflow-gpu

**Comment by MarkSCQ** [comment]
> Did you install tensorflow-gpu or tensorflow? You will need tensorflow-gpu

I did. Thank you for your information, from another post. :smiley:

**Comment by Shawn-Shan** [comment]
I see.. then were you able to use your GPU to run other keras code previously? Like keras examples etc.

**Comment by MarkSCQ** [comment]
> I see.. then were you able to use your GPU to run other keras code previously? Like keras examples etc.


Now I can use CPU after downgrading the h5py, but using GPU is still a problem even if using -g 0 or --gpu 0. I think the reasons are Cuda and cuDNN versions. 
I am now using Cuda 10.1, apparently, TF 1.14.0 won't work with 10.1 from the link below. I need to prepare another version of Cuda and cuDNN. This link contains the TF Cuda versions pairs under Linux and Windows. I am gonna figure it out recently. 
It would be better to add some contents of this link to Readme.md file I think.
Thank you!
[https://www.tensorflow.org/install/source_windows](url)

**Comment by Shawn-Shan** [comment]
Ah I see. We are using CuDA-9.0 I believe. The tensorflow version shouldn't matter that much, as long as it is tensorflow 1.

**Comment by MarkSCQ** [comment]
> Ah I see. We are using CuDA-9.0 I believe. The tensorflow version shouldn't matter that much, as long as it is tensorflow 1.

It's a problem for me. I am using Cuda 10 with the latest TF. I am trying using WSL-NV docker recently. Trying to find a way to build it.
