### ISSUE TITLE
Doesn't protect against Face++ Recognition in my test

### ISSUE THREAD

**Issue by herryzhang** [Shawn-Shan/fawkes#67]
1.   I have 11picture,two person
![image](https://user-images.githubusercontent.com/8223359/90313266-c0457d00-df3d-11ea-8319-e04435c2af35.png)
2.   I use Fawkew protect lyf1.jpg    lyf2.jpg    lyf3.jpg
![image](https://user-images.githubusercontent.com/8223359/90313293-0569af00-df3e-11ea-957f-d23764a51f5c.png)
and the
![image](https://user-images.githubusercontent.com/8223359/90313298-12869e00-df3e-11ea-8a9f-37cdd27b46b3.png)
3.     I use Face++ search Api test
3.1   8 original images not protected
![image](https://user-images.githubusercontent.com/8223359/90313356-76a96200-df3e-11ea-9560-8752b0eb3dff.png)
3.2    I use three protect picture test
lyf1_min_cloaked.png、lyf2_min_cloaked.png、lyf3_min_cloaked.png
![image](https://user-images.githubusercontent.com/8223359/90313378-b3755900-df3e-11ea-8838-e95bf0aa8fc1.png)
![image](https://user-images.githubusercontent.com/8223359/90313391-c4be6580-df3e-11ea-9736-205cf4212ae4.png)
![image](https://user-images.githubusercontent.com/8223359/90313398-cf78fa80-df3e-11ea-9fe8-1f6edbdcc6f5.png)
But it's not what we expected

**Comment by Shawn-Shan** [comment]
Hi Harry, 

A couple things: 
1. Please do not use celebrity pictures for test. Because most of the facial recognition models have already trained on celebrities. Which means they already have the unprotected images. 
2. You need a lot more than 2 classes in the model for the test. Intuitively, it is much easier to hide yourself in 10,000 other people than hide in 2 people only. In our test, we use the WebFace dataset, which has 10K+ labels. You will need to use the Face++ API for the scalable test. We will shortly provide a script that does that for Azure. 

For evaluation, we are planning to release a script with a local facial recognition model to help you whether the protection is successful. 

Best, 
Shawn

**Comment by herryzhang** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Thanks for your explanation and tips. best,Herry
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                858570636
                            
                    
                        
                            
                                    858570636@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 8/15/2020 23:59，Shawn Shan<notifications@github.com> wrote： 



Hi Harry,
A couple things:

Please do not use celebrity pictures for test. Because most of the facial recognition models have already trained on celebrities. Which means they already have the unprotected images.
You need a lot more than 2 classes in the model for the test. Intuitively, it is much easier to hide yourself in 10,000 other people than hide in 2 people only. In our test, we use the WebFace dataset, which has 10K+ labels. You will need to use the Face++ API for the scalable test. We will shortly provide a script that does that for Azure.

For evaluation, we are planning to release a script with a local facial recognition model to help you whether the protection is successful.
Best,
Shawn

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by csjunjun** [comment]
Dear Dr. Shawn,
    Sorry to interrupt you, I also have the same problem as Harry and hope to test Face++. I would appreciate it if you could send me a script. My e-mail address is junlwind@163.com
    What is more, the feature extractors in Table 1 of your paper are Web-Incept, Web_Dense, VGG2_Incept and VGG2_Dense. But in this release code, there are only extractors_0 and extractors_2. Can you kindly tell me what architectures and datasets these extractors is based on？ and is that possible to release adversarial training versions? Since in this paper you claimed that the adversarial training models performance better in the wild.

Thank you so much for spending time on my questions!
Jun.
