### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.platform'

### ISSUE THREAD

**Issue by biergaiqiao** [Shawn-Shan/fawkes#68]
May I ask a question, i meet a problem, I use tensorflow1.14 ,windows10 os，when i imput import fawkes in python mode of cmd. It doesn't work.Why?
![image](https://user-images.githubusercontent.com/49507460/90330025-47e1c900-dfdc-11ea-9779-f9c49c2fb6fe.png)

**Comment by emjoywill** [comment]
Make sure you have tensorflow==1.14.0 installed on your computer. You can do this by running "pip uninstall tensorflow" and then "pip install tensorflow==1.14.0"

**Comment by FedericoTartarini** [comment]
I have tried the above suggestion but I am getting the following error:

```
PS C:\Users\sbbfti> pip3 install tensorflow==1.14.0
ERROR: Could not find a version that satisfies the requirement tensorflow==1.14.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.14.0
```

**Comment by emjoywill** [comment]
What version of Python are you running? If your version of Python is >= 3.8, it will not be compatible with our software and you will not be able to download tensorflow==1.14.0. You will need to downgrade to Python<=3.7.

**Comment by FedericoTartarini** [comment]
Thank you very much for letting me know.
