### ISSUE TITLE
Clarify usage rights

### ISSUE THREAD

**Issue by smaffulli** [Shawn-Shan/fawkes#69]
Currently, the repository seems to be licensed under the [BSD 3-clause license](https://github.com/Shawn-Shan/fawkes/blob/master/LICENSE) but the COPYRIGHT section in the Readme says `This code is intended only for personal privacy protection or academic research.` The two are in conflict.

Can you please clarify what are the usage, modification and distribution rights of your code? Thank you.

**Comment by prasket** [comment]
I would also like some clarification around this.

**Comment by arthurlataks** [comment]
I would also like some clarification around this.

**Comment by Shawn-Shan** [comment]
We came to aware that several groups have been using our code base to build APIs and APPs. From now on, we will follow BSD-3 as our license. But for all other versions, our team is not involved in any of the implementation, and thus not responsible for any issues.

**Comment by smaffulli** [comment]
@Shawn-Shan Glad to read that. I think you should clarify that in the README. As it's written now, is is not clear what the terms of usage are.
