### ISSUE TITLE
Error in arch says: Illegal Hardware instructions

### ISSUE THREAD

**Issue by void00r** [Shawn-Shan/fawkes#7]
OS: Artix Linux x86_64
Shell: zsh and bash (tried on both)
```
./protection -d ~/Pictures/hawkes/
zsh: illegal hardware instruction  ./protection -d ~/Pictures/hawkes
```

**Comment by Shawn-Shan** [comment]
I believe this is a OS specific error and I am not sure how to solve. 

You can search up it on stackoverflow. Or clone the source code, and run using python.

**Comment by PHPoenX** [comment]
@void00r @Shawn-Shan no, it is problem of tensorflow.

https://github.com/tensorflow/tensorflow/issues/17411 https://stackoverflow.com/a/49169125/12309508

Possible solution - rebuilding tensorflow
