### ISSUE TITLE
Good idea- but W10 only.

### ISSUE THREAD

**Issue by Eleventythreeve** [Shawn-Shan/fawkes#70]
Hi,

We love the idea- but limiting it to stinky Windows 10 isn't a good idea. W10 is the most spying version yet. It should be extended at least as far back as 8 and 7.

We are a couple and we both took our 10 computers and switched to 10 only running in a VM once every blue moon. 10 SUCKS!!!

**Comment by emjoywill** [comment]
I'm sorry we haven't provided Windows compatibility to suit your needs. Our own access to non-W10 systems is currently limited due to the pandemic. Providing greater Windows compatibility is certainly on our future todo list.

**Comment by tredondo** [comment]
If you care about privacy, you shouldn't be using Windows to begin with.
