### ISSUE TITLE
Not specifying -d should default to ./

### ISSUE THREAD

**Issue by tredondo** [Shawn-Shan/fawkes#73]
Without `-d`, fakwes could default to the current directory.

**Comment by Shawn-Shan** [comment]
That is correct. You should always specify `-d`

**Comment by tredondo** [comment]
Sorry, my issue title was unclear.

What I meant was, if I don't specify `-d`, I would like Fawkes to process files from the current directory.

**Comment by emjoywill** [comment]
Thanks for the input! We will keep this in mind for future releases. Also, you are welcome to fork the codebase and make changes like this that would make the code more usable for your specific needs.
