### ISSUE TITLE
Add advice on protection best practices

### ISSUE THREAD

**Issue by tredondo** [Shawn-Shan/fawkes#74]
Consider a user has only one image they want to cloak. Since a new run on the same source image generates a new cloaked image, should a user run Fawkes once and upload that one cloaked image to all their social media accounts, or should they run Fakwes multiple times and upload different results to their different social media accounts (eg profile pics)?

**Comment by Shawn-Shan** [comment]
We recommend users to just do one run and upload to all their social media accounts.
