### ISSUE TITLE
fail to run protection.py

### ISSUE THREAD

**Issue by Suqingyong** [Shawn-Shan/fawkes#75]
Dear sir, I failed to run protection.py, there was an error "no module named fawkes",  I was really confused. Would you mind helping me to solve the problem ,sir. Thanks you.

**Comment by Shawn-Shan** [comment]
Are you running using the binary version or through source code?

**Comment by MarkSCQ** [comment]
> Are you running using the binary version or through source code?

  File "protection.py", line 226, in <module>
    main(*sys.argv)
  File "protection.py", line 211, in main
    protector = Fawkes(args.feature_extractor, args.gpu, args.batch_size)
  File "protection.py", line 54, in __init__
    self.feature_extractors_ls = [load_extractor(name) for name in self.fs_names]
  File "protection.py", line 54, in <listcomp>
    self.feature_extractors_ls = [load_extractor(name) for name in self.fs_names]
  File "E:\Python3.6.5\lib\site-packages\fawkes\utils.py", line 406, in load_extractor
    model = keras.models.load_model(model_file)
  File "E:\Python3.6.5\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "E:\Python3.6.5\lib\site-packages\keras\engine\saving.py", line 550, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "E:\Python3.6.5\lib\site-packages\keras\engine\saving.py", line 242, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'

I am using Tensorflow 1.12.0 Keras 2.2.5 python 3.6.5 and I got this error. It seems I need to upgrade the version, but I am not sure. Can you offer your runnable environment? Trials over different versions of libraries will consume huge time. 
Thanks

**Comment by sigseg5** [comment]
> Are you running using the binary version or through source code?

Same issue with `fawkes` package from PyPi. Runned with Python 3.7 at Docker, all dependences automatically installed with `fawkes` package + my own packages.

Installed packages:
```
absl-py              0.11.0
APScheduler          3.6.3
astor                0.8.1
bleach               3.2.1
cached-property      1.5.2
certifi              2020.11.8
cffi                 1.14.3
cryptography         3.2.1
decorator            4.4.2
fawkes               0.3.2
gast                 0.2.2
google-pasta         0.2.0
grpcio               1.33.2
h5py                 3.1.0
importlib-metadata   2.0.0
Keras                2.3.1
Keras-Applications   1.0.8
Keras-Preprocessing  1.1.2
Markdown             3.3.3
numpy                1.16.4
opt-einsum           3.3.0
packaging            20.4
Pillow               8.0.1
pip                  20.2.4
protobuf             3.13.0
pycparser            2.20
pyparsing            2.4.7
python-telegram-bot  13.0
pytz                 2020.4
PyYAML               5.3.1
scipy                1.5.4
setuptools           50.3.2
six                  1.15.0
tensorboard          1.15.0
tensorflow           1.15.0
tensorflow-estimator 1.15.1
termcolor            1.1.0
tornado              6.1
tzlocal              2.1
webencodings         0.5.1
Werkzeug             1.0.1
wheel                0.35.1
wrapt                1.12.1
zipp                 3.4.0
```

Traceback:
```bash
Download models...
Traceback (most recent call last):
  File "/usr/local/bin/fawkes", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/fawkes/protection.py", line 210, in main
    protector = Fawkes(args.feature_extractor, args.gpu, args.batch_size)
  File "/usr/local/lib/python3.7/site-packages/fawkes/protection.py", line 53, in __init__
    self.feature_extractors_ls = [load_extractor(name) for name in self.fs_names]
  File "/usr/local/lib/python3.7/site-packages/fawkes/protection.py", line 53, in <listcomp>
    self.feature_extractors_ls = [load_extractor(name) for name in self.fs_names]
  File "/usr/local/lib/python3.7/site-packages/fawkes/utils.py", line 411, in load_extractor
    model = keras.models.load_model(model_file)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 273, in _deserialize_model
    model_config = json.loads(model_config.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by MarkSCQ** [comment]
> > Are you running using the binary version or through source code?
> 
> Same issue with `fawkes` package from PyPi. Runned with Python 3.7 at Docker, all dependences automatically installed with `fawkes` package + my own packages.
> 
> Installed packages:
> 
> ```
> absl-py              0.11.0
> APScheduler          3.6.3
> astor                0.8.1
> bleach               3.2.1
> cached-property      1.5.2
> certifi              2020.11.8
> cffi                 1.14.3
> cryptography         3.2.1
> decorator            4.4.2
> fawkes               0.3.2
> gast                 0.2.2
> google-pasta         0.2.0
> grpcio               1.33.2
> h5py                 3.1.0
> importlib-metadata   2.0.0
> Keras                2.3.1
> Keras-Applications   1.0.8
> Keras-Preprocessing  1.1.2
> Markdown             3.3.3
> numpy                1.16.4
> opt-einsum           3.3.0
> packaging            20.4
> Pillow               8.0.1
> pip                  20.2.4
> protobuf             3.13.0
> pycparser            2.20
> pyparsing            2.4.7
> python-telegram-bot  13.0
> pytz                 2020.4
> PyYAML               5.3.1
> scipy                1.5.4
> setuptools           50.3.2
> six                  1.15.0
> tensorboard          1.15.0
> tensorflow           1.15.0
> tensorflow-estimator 1.15.1
> termcolor            1.1.0
> tornado              6.1
> tzlocal              2.1
> webencodings         0.5.1
> Werkzeug             1.0.1
> wheel                0.35.1
> wrapt                1.12.1
> zipp                 3.4.0
> ```
> 
> Traceback:
> 
> ```shell
> Download models...
> Traceback (most recent call last):
>   File "/usr/local/bin/fawkes", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/fawkes/protection.py", line 210, in main
>     protector = Fawkes(args.feature_extractor, args.gpu, args.batch_size)
>   File "/usr/local/lib/python3.7/site-packages/fawkes/protection.py", line 53, in __init__
>     self.feature_extractors_ls = [load_extractor(name) for name in self.fs_names]
>   File "/usr/local/lib/python3.7/site-packages/fawkes/protection.py", line 53, in <listcomp>
>     self.feature_extractors_ls = [load_extractor(name) for name in self.fs_names]
>   File "/usr/local/lib/python3.7/site-packages/fawkes/utils.py", line 411, in load_extractor
>     model = keras.models.load_model(model_file)
>   File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
>     return load_function(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 584, in load_model
>     model = _deserialize_model(h5dict, custom_objects, compile)
>   File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 273, in _deserialize_model
>     model_config = json.loads(model_config.decode('utf-8'))
> AttributeError: 'str' object has no attribute 'decode'
> ```

I tried many pairs under WSL, and they all fail, I don't want to dive into Keras and change the code, it's dangerous. I find one solution on StackOverflow, but it won't work from my side. Here is the link [https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi](url)

**Comment by Shawn-Shan** [comment]
You will need to downgrade your h5py to 2.10.0, as stated in this [answer](https://stackoverflow.com/questions/53740577/does-any-one-got-attributeerror-str-object-has-no-attribute-decode-whi)

**Comment by sigseg5** [comment]
> downgrade your h5py to 2.10.0

Works perfectly, thanks!

**Comment by xirkus** [comment]
No installation required: https://dev.scrb.ai

**Comment by Karol-G** [comment]
Hi,

I had the same error and downgraded h5py, but now I get the following error:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\me\Anaconda3\envs\fawkes\lib\site-packages\keras\engine\saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\me\Anaconda3\envs\fawkes\lib\site-packages\keras\engine\saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\me\Anaconda3\envs\fawkes\lib\site-packages\keras\engine\saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\me\Anaconda3\envs\fawkes\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "C:\Users\me\Anaconda3\envs\fawkes\lib\site-packages\keras\utils\generic_utils.py", line 140, in deserialize_keras_object
    ': ' + class_name)
ValueError: Unknown layer: Functional
```

I am using the newest fawkes source code with the following library versions:

h5py = 2.10.0
keras = 2.3.1
python = 3.7.10
tensorflow = 2.0.0

Best
Karol

**Comment by sigseg5** [comment]
> I had the same error and downgraded h5py, but now I get the following error:


Did you sure that u use actual version? All works fine with fawkes==1.0.2, with out downgrading h5py

**Comment by Karol-G** [comment]
Yes. What keras and tensorflow do you have?

**Comment by sigseg5** [comment]
> Yes. What keras and tensorflow do you have?

```
tensorboard            2.4.1
tensorboard-plugin-wit 1.8.0
tensorflow             2.4.1
tensorflow-estimator   2.4.0
```
