### ISSUE TITLE
target_data

### ISSUE THREAD

**Issue by Suqingyong** [Shawn-Shan/fawkes#77]
dear sir,  due to the limitation of network in the testing environment of our machine, we could not download the target data running the process successfully, are there any other way to download the target_data? thank you.

**Comment by Shawn-Shan** [comment]
The servers we have are under the same domain, so I think changing a hosting machine won't help. It is really hard to host ~10G data high bandwidth through other means. 

Could you try some different network connection on your side? The data you need to download is probably small (~100MB).
