### ISSUE TITLE
About featrue extractor

### ISSUE THREAD

**Issue by biergaiqiao** [Shawn-Shan/fawkes#80]
Hello, would you please tell me something about the high_extract in your git_hub code? What's the name of your feature extracter?
![image](https://user-images.githubusercontent.com/49507460/91987512-beaeee00-ed60-11ea-9232-ddfeb186b9ad.png)

**Comment by Shawn-Shan** [comment]
The feature extractor we used is download via this [link](http://mirror.cs.uchicago.edu/fawkes/files/high_extract.h5).
