### ISSUE TITLE
"No face detected" even if obviously a face is shown  

### ISSUE THREAD

**Issue by napolitano** [Shawn-Shan/fawkes#81]
fawkes shows often "No face detected" message and simply rejects processing of input data - even if obviously a face is visible. This mainly happens if glasses (especially sunglases) were involved or other more or less visible accessoir.

However thios reduces worth of the tool to some degree as also faces with glasses or other accessoirs may be exposed to learning algorithms.

**Comment by emjoywill** [comment]
Thanks for letting us know! Sunglasses cover the parts of the face that are most important for classification (i.e. around the eyes), so it makes sense that these sorts of images fail the face detection stage. We currently rely on an external package (MTCNN) to perform face detection. We can look at upgrading this to a more powerful detector in future versions.
