### ISSUE TITLE
testing protection effectiveness is needed

### ISSUE THREAD

**Issue by mofanv** [Shawn-Shan/fawkes#82]
Hi,

Thanks for the nice work. I have tried fawkes to generate private images, it is kind of cool and the tool is very handy. However, I still don't find an empirical way or test to convince myself the protection is true. According to #59 #67, trying to test the effectiveness in our ways might be failed. As said in readme file, the test is actively worked on and will be ready shortly. So I wonder could you please provide at least one example for us to verify the protection?

Thank you very much!
Best,
Fan

**Comment by MoralCode** [comment]
to add to this a little bit, i would also find it useful to use a tool like this to compare the cloaking effectiveness of fawkes to the effectiveness of other methods that manipulate the image in barely-perceptible ways such as retouching an image with photoshop (mainly just for the curiosity).
