### ISSUE TITLE
Best Practices?

### ISSUE THREAD

**Issue by natedl98** [Shawn-Shan/fawkes#84]
Hi, love the algo, but have a couple questions

First of all, we had it running on an AWS EC2 and it took 15 minutes to do a single image on high protection mode. So we installed it on a GPU instance (p3.2xlarge) and then it still took 9 minutes :/ 

This doesn't seem correct based on the readme. We're unsure of what to use as the --gpu option. Could that be our problem? Not sure what GPU ID is, but when I looked at the code, I saw it ended up configuring an environment variable CUDA_VISIBLE_DEVICES, and other people just used values like "0" (which is the default) or "1"

Also, is there any way to just run it on a single image, instead of specifying a directory? 

Thanks!

**Comment by Shawn-Shan** [comment]
Thanks for the comments. If you only have 1 GPU on your machine, you should use CUDA_VISIBLE_DEVICES='0'. 

Currently, you can only run a directory (but you can have only 1 image in the directory). We will add single image option in the future.

**Comment by natedl98** [comment]
ok thanks. am I doing something wrong if it is taking 9 minutes?

> Thanks for the comments. If you only have 1 GPU on your machine, you should use CUDA_VISIBLE_DEVICES='0'.
> 
> Currently, you can only run a directory (but you can have only 1 image in the directory). We will add single image option in the future.
