### ISSUE TITLE
Does the GPU really work in the gpu mode?

### ISSUE THREAD

**Issue by biergaiqiao** [Shawn-Shan/fawkes#88]
![image](https://user-images.githubusercontent.com/49507460/94556958-841d7000-0290-11eb-90b7-62215c5e4a4d.png)
![image](https://user-images.githubusercontent.com/49507460/94557040-9c8d8a80-0290-11eb-8312-ee7f04223611.png)
![image](https://user-images.githubusercontent.com/49507460/94557061-a1ead500-0290-11eb-997d-d6f7dbcf5927.png)

**Comment by biergaiqiao** [comment]
you can see the rate of cpu is 1005 while the gpu is only 3%;Why?

**Comment by biergaiqiao** [comment]
and I have pip install the tensorflow-gpu ==1.14.0

**Comment by Shawn-Shan** [comment]
This is definitely not as expected. On our machine, we utilize GPU to >80%. 

Did you set the --batch-size option to a high number? (ie 16, 32). 

It takes 1 mins to process 64 images on our machine.
