### ISSUE TITLE
"EOFError: Ran out of input" Error - PC

### ISSUE THREAD

**Issue by aendia777** [Shawn-Shan/fawkes#9]
Followed the process outlined in _https://github.com/Shawn-Shan/fawkes/blob/master/fawkes/README.md_ and attempted to cloak 2x *.jpg and 1x *.png image. In all instances, I received the following 2 error lines: "EOFError: Ran out of input
[12264] Failed to execute script protection". This was attempted on Windows 10 Version 2004.

A screenshot of my Powershell session is located below. Any assistance would be appreciated... I would really like to get this facial recognition obfuscation program working if possible!

![image](https://user-images.githubusercontent.com/68583528/88023107-1289ae80-caf6-11ea-94dc-50b15fc53d1b.png)

**Comment by Shawn-Shan** [comment]
It seems one downloaded file is corrupted. Can you `rm -r C:\User\USERNAME\.fawkes`? Then run the code again?

**Comment by aendia777** [comment]
@Shawn-Shan That worked, thanks. This program is groundbreaking, and worked perfectly for my use-case! Keep up the great work, I'll be excited to see how this project develops
