### ISSUE TITLE
The pixels of the cloaked in your github resposity is different with the original one

### ISSUE THREAD

**Issue by biergaiqiao** [Shawn-Shan/fawkes#91]
Hello,sir, my I have a question please? When I process a photo in m*n by your open source code, I got a 224*224, but now I wonna get the cloaked image with m*n pixels,what  should I do ?Thank you very much!!!!
the first one is by the source code in 'min' mode
the second one is by the cmd in 'min' mode

![Ivanka_Trump_min_cloaked](https://user-images.githubusercontent.com/49507460/95668109-f439c900-0ba1-11eb-86b1-3d3b14128449.jpeg)
![Ivanka_Trump_min_cloaked](https://user-images.githubusercontent.com/49507460/95668119-1fbcb380-0ba2-11eb-8b53-c16df1680035.png)

**Comment by emjoywill** [comment]
Fawkes is currently designed to output 224x224 images. You can resize the image using different software tools if you would like after cloaking. Adding support for different image sizes is on our "improvements" list.
