### ISSUE TITLE
Can I run Fawkes-0.3.1.exe on Win7?

### ISSUE THREAD

**Issue by spooke-hunter** [Shawn-Shan/fawkes#92]
I have downloaded Fawkes v0.3.1 for Windows. Tried executing it on Win7. I get error message "Failed to execute script app_qt". I have re-downloaded the file several times but same error. Do I need some additional install/patch to get it working (python, tensorflow)?? Anyone?

**Comment by emjoywill** [comment]
Unfortunately, the current version of the Fawkes Windows app is only compatible with Windows 10+.
