### ISSUE TITLE
fatal error running Fawkes-0_3_1exe

### ISSUE THREAD

**Issue by algis1960** [Shawn-Shan/fawkes#93]
When I run the exe, I get the following error-window:
fatal error running Fawkes-0_3_1exe
Windows 10 Home Failed to execute script app_qt

**Comment by nottheend** [comment]
Same here

**Comment by emjoywill** [comment]
What version of Windows are you running? The current app is only compatible with Windows 10+.

**Comment by nottheend** [comment]
Windows10

**Comment by zhbn** [comment]
Same here

**Comment by zhbn** [comment]
> When I run the exe, I get the following error-window:
> fatal error running Fawkes-0_3_1exe
> Windows 10 Home Failed to execute script app_qt

Same here

**Comment by ac-sudo** [comment]
Same here

**Comment by xirkus** [comment]
No installation required: https://dev.scrb.ai

**Comment by nottheend** [comment]
@xirkus Do you know the underlying source?

**Comment by xirkus** [comment]
@nottheend Sorry, I didn't use the Windows installer for fawkes. I suspect it has to do with the way the .exe is packaged [Windows- Pyinstaller Error “failed to execute script ” When App Clicked](https://stackoverflow.com/questions/40716346/windows-pyinstaller-error-failed-to-execute-script-when-app-clicked).

Alternatively, you can avoid installing and just use the web app ;-)

**Comment by nottheend** [comment]
Thanks @xirkus , sounds reasonable with the failure message what you posted in the link.

What I wanted to know: Is the same source code used in the web app you linked?

**Comment by xirkus** [comment]
actually running the latest version (1.0.2)

**Comment by Shawn-Shan** [comment]
Please try the newest released Window's app
