### ISSUE TITLE
Windows binary output indicates progress of image processed, not face

### ISSUE THREAD

**Issue by gsAoNXT4LLRVY6nu** [Shawn-Shan/fawkes#94]
Windows binary protection-v0.3.exe outputs processing of facial images with format:
     "processing image 1 at 2020-10-15 12:01:02.123456"
Here, "image 1" indicates the processing of a single FACE, not an IMAGE FILE.
The output is confusing because the terms "image" and "face" are used to identify the image file and the faces in each file, respectively, in the face-identification phase of the process. The term "image" in the output above though represents the face, not the image file.
The output would better serve the user by indicating which face in what file is currently being proccessed. For example:
     "processing face 1 in image 1 at 2020-10-15 12:01:02.123456
      processing face 2 in image 1 at 2020-10-15 12:01:48.123456".
This would prevent a user from underestimating the total time to completion if there are more total faces to process than there are number of files (which I did).

**Comment by Shawn-Shan** [comment]
That is a good suggestion. We will fix this in the next release.
