### ISSUE TITLE
Do all cloaked images of me show the same cloaked person for face recognition software?

### ISSUE THREAD

**Issue by Karol-G** [Shawn-Shan/fawkes#95]
Hi,

there are most likely no images of me online anywhere in the internet. If I make a bunch of pictures of me now, cloak them and upload them to the internet, would face recognition software recognize the same cloaked person on all these pictures? If yes, would it be possible to cloak the images in a way that face recognition software would not even be able to recognize that there is the same cloaked person on all the pictures. Meaning, that it thinks that each of the images shows a different person.

Best
Karol

**Comment by Shawn-Shan** [comment]
Hi Karol, 

Yes that is correct. A facial recognition system will recognize all the cloaked image of you as the same person. It would be great to make all images to appear as different person. But it is a much harder task and we can't support that currently.
