### ISSUE TITLE
Fawkes does not run on macOS Big Sur

### ISSUE THREAD

**Issue by TriangleJuice** [Shawn-Shan/fawkes#98]
The application launches and is visible in the Dock, but does not show any window. Right-clicking on the Dock icon reveals that the application is not responding.

**Comment by Shawn-Shan** [comment]
I have realized this as well, probably need to recompile on the new OS. I will find some time to do that after thanksgiving. In the meantime, you can always use the source code.

**Comment by TriangleJuice** [comment]
Thanks, I will try that in the meantime. Happy Thanksgiving!

**Comment by Shawn-Shan** [comment]
Ok it is fixed. You can download the new version 0.3.1 .dmg on our website. 

The issue is related to PyQT5's compatibility on mac big sur.

**Comment by TriangleJuice** [comment]
I tested it out and everything works as advertised! Thank you.

**Comment by PaulSherp** [comment]
Version 0.3.1 does not appear to be working under macOS Big Sur 11.2 beta (20D5029f). As indicated in the OP, the application launches and is visible in the Dock, but does not show any window. Right-clicking on the Dock icon reveals that the application is not responding.
